### ISSUE TITLE
Bom versioning question

### ISSUE THREAD

**Issue by jangalinski** [AxonFramework/axon-bom#2] opened 2021-01-28 16:18 UTC
1st: cool that there is a BOM now

2nd: Question: what is your versioning idea? coupling the extension versions to the axon-framework release versions seems a bit strange to me ... when 4.5 main release is out and we adopt for example extension-kotlin to support new features of 4.5 this will result in a new version of extension-kotlin and thus will require a new bom release ...  

Possible Solutions:

* provide two boms: one just containing the "main" axon-framework components released under 4.5 (or 4.4.7, ...) and one that is released more frequently, referring to the first one and updating extension versions
* a versioning scheme that contains the main framework version but supports an additional version counter to reflect intermediate changes extensions, which could either be a four digit version (4.4.6.1) or a suffixed version (1.2.3-A4.4.6) where the part after the "-" is the main framework version and the part before the continuing  version of the bom artifact.

Did you consider this? What is the plan, what's your opinion?

**Comment by azzazzel** [comment] 2021-01-28 17:33
Hi Jan,

as a matter of fact that is the exact issue we are discussing internally currently and the main reason why the BOM is not released on Maven Central yet. I'm personally in favour of something similar to the second option you propose but it has its drawbacks. 
As for the plan, I think we'll need a bit more time to consider all options and decide what will be the best _(taking into account both usage convenience and release effort)_ approach. Of course your feedback is much appreciated. Should you have any more ideas or concerns please do not hesitate to share them.

**Comment by jangalinski** [comment] 2021-02-13 08:56
Please have a look at: https://github.com/AxonFramework/AxonFramework/pull/1707

I would prefer it over this additional repository.

This repository could still provide a bom that is more like the spring-boot-dependencies pom ... so it will reference the axon-framework-bom but also extensions, 3rd party libs and so on ... 

but https://github.com/AxonFramework/AxonFramework/issues/1200 will be fixed by the PR ..

**Comment by azzazzel** [comment] 2021-03-09 14:53
Hi Jan,

let me start by posting something that we can use as reference. The table below is what would the versions look like if we were to apply it to the `4.4` framework and relevant extensions. _**PLESE NOTE: we are not going to release BOMs for already existing framework/extensions versions. This is just for visualisation purposes during this conversation**_

![image](https://user-images.githubusercontent.com/33792/110465774-2742a300-80d5-11eb-8df9-1dae27bb4840.png)

A couple of things to note there:

- 2 or more extensions can be released together and that would result in only one new BOM release
- extensions can be released together with the framework and that would also result in single new BOM release

The table also clearly demonstrates the version mismatch issue you are taking about. We are fully aware of that and here is what we'll do to mitigate it.

- all future versions will be in `x.y.z` format. So there will be no `4.5` nor `5.0`. Instead there will be `4.5.0` and `5.0.0` respectively. We want to avoid any possible confusion and introduce version format consistency.
- the major and the minor version of the BOM will always match the major and the minor version of the framework. That is to say that a BOM versioned `4.5.x` can contain framework version `4.5.x` but not `4.4.x`, `4.6.x` nor `5.0.x` 
- we have a build step in the BOM that prevents building and realising an unresolvable BOM _(one that links to artifacts not available in Maven Central)_. Therefore using the BOM is as safe as using the direct framework dependency.
- starting with `4.5.0` the **BOM version will be the main version**. We'll use the BOM version instead of framework's version everywhere we refer to AxonFramework (download page, documentation, tutorials, blogs, ...). 
- we are thinking of creating an automated process that will publish a mapping between BOM versions and the versions of the artifacts it contains in more user friendly from than the POM. That should help those who want/need to stick to a specific framework versions insisted. 
- we'll be advising people to upgrade every time a new BOM version is released. There are 2 aspects that can be perceived as issues with that change:
  - failure to guarantee extensions & framework compatibility - Currently an attempt to use incompatible versions is a misconfiguration error on the user side. Moving towards BOM creates the expectation that compatibility should be now guaranteed by the release itself. In reality, currently there are no explicit tests to provide such guarantee with every release. However given that 
    - extensions depend on particular version of the framework are always released with or after the respective framework version.
    - framework patch releases (where only the last digit changes) should alway be backwards compatible 
    - every component(s) release is followed by a new BOM releases 
  
    the BOM will essentially prevent the above mentioned misconfiguration issues from occurring. There of course can be incompatibility issues caused by bugs or other factors but it's not the purpose of the BOM to solve those.      
  - enforce needles upgrades - For example from the table above it's clear that upgrading from BOM `4.4.1` to `4.4.3` has no value for any project that makes no use of `amqp`, `jgroups`, `mongo` or `kotlin` extensions. The BOM versioning schema does not make that explicit though. But when you think about it, that's exactly the case we have currently. An upgrade to any given framework version may be needless as it may contain changes that are solely in areas/modules that given application is not using. Never the less we do recommend to upgrade when possible. Opportunities to upgrade the BOM will indeed occur more often that those to upgrade the framework. But such upgrades will literally introduce no changes if the project does not depend on any of the changed artifacts. 

I hope the above explains well the motivation behind the change and the plan. Overall I see it as significant improvement over the current situation at the cost of few minor drawbacks. If there are any concerns about it though that the above explanation does not cover please do not hesitate to raise them.

**Comment by jangalinski** [comment] 2021-03-09 16:02
Thank you for that explanation. Yes, if the bom is leading, the problems I raised seem to be fixed.
So let's see how it goes.

**Comment by zambrovski** [comment] 2021-03-17 10:17
Can't wait to get it from central...

**Comment by smcvb** [comment] 2021-04-02 12:48
Closing this issue, as it's a question.
By the way, currently working on getting this guy out there so it can be used by everybody :-)

**Closed by smcvb** 2021-04-02 12:48 UTC
Labels: Type: Question
